#!/bin/sh

xrandr \
	--output DP-1 \
	--primary \
	--mode 1920x1080 \
	--pos 0x840 \
	--rotate normal \
	--output HDMI-2 \
	--output eDP-1 \
	--mode 1920x1080 \
	--pos 1920x1016 \
	--rotate normal \
	--output HDMI-1 \
	--mode 1920x1080 \
	--pos 3840x0 \
	--rotate left
