#!/bin/sh

unalias -a

alias sudo="sudo " # allow alias for sudo

# dotfiles
[ -d "$HOME/.dotgit" ] && alias dotgit='/usr/bin/git --git-dir=$HOME/.dotgit/ --work-tree=$HOME' && alias d="dotgit "

# use colors
alias cal="cal -m --color=always"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ls="ls -hN --color=auto"

# default flags
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias df="df -h"
alias free="free -h"

# replace
alias top="htop"

# custom
alias hg="history 1 -1 | rg"
alias ll="ls -alF --group-directories-first"
alias mkd="mkdir -pv"

# shortcuts
alias z="zathura"

# lynx
[ -d ${XDG_CONFIG_HOME}/lynx ] && \
    alias lynx="lynx -cfg=${XDG_CONFIG_HOME}/lynx/lynx.cfg -lss=${XDG_CONFIG_HOME}/lynx/lynx.lss"
alias "?"="search-with-lynx "
alias "?b"="search-with-lynx bind "
alias "?d"="search-with-lynx duck "
alias "?g"="search-with-lynx google "

# editor
[ -x "$(command -v ed)" ] && alias ed="vi"
[ -x "$(command -v vim)" ] && alias vi="vim"
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

if [ -v EDITOR ]; then
	alias v=$EDITOR
	alias e=$EDITOR
fi

# sudo
for cmd in emaint emerge eselect mount umount poweroff reboot shutdown showkey su ; do
	alias $cmd="sudo $cmd "
done; unset cmd;

alias emerge="sudo emerge --ask"

