#!/bin/sh

unalias -a

# git
alias gst="git status"
alias gpl="git pull"

# dotfiles
[ -d "$HOME/.dotgit" ] \
    && alias dotgit='/usr/bin/git --git-dir=$HOME/.dotgit/ --work-tree=$HOME' \
    && alias d="dotgit "

if command -v lazygit &> /dev/null ; then
    alias "lg"="lazygit"
    alias "dotgit-lazy"="lazygit --git-dir=$HOME/.dotgit/ --work-tree=$HOME"
    alias "dlazy"="dotgit-lazy"
fi

# use colors
alias cal="cal -m --color=always"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ls="ls -hN --color=auto"

# default flags
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias df="df -h"
alias free="free -h"

# replace
alias top="htop"

# custom
alias hg="history 1 -1 | rg"
alias ll="ls -alF --group-directories-first"
alias mkd="mkdir -pv"
alias mnote='mkd "$HOME/Notes" && nvim "$HOME/Notes/$(date +%F)"'
alias mnote-now='mkd "$HOME/Notes" && nvim "$HOME/Notes/$(date +%F_%T)"'

# lynx
[ -d ${XDG_CONFIG_HOME}/lynx ] && \
    alias lynx="lynx -cfg=${XDG_CONFIG_HOME}/lynx/lynx.cfg -lss=${XDG_CONFIG_HOME}/lynx/lynx.lss"

# armcord/discord
[ -f ${HOME}/.submodules/armcord/dist/linux-unpacked/armcord ] && \
    alias armcord="${HOME}/.submodules/armcord/dist/linux-unpacked/armcord"
alias discord="armcord"
if command -v armcord > /dev/null && pidof -sx dbus-daemon > /dev/null ; then
    alias armcord="DBUS_SESSION_BUS_ADDRESS=\"autolaunch:\" ${HOME}/.submodules/armcord/dist/linux-unpacked/armcord"
fi

if command -v search-with-lynx &> /dev/null ; then
    alias "?"="search-with-lynx "
    alias "?b"="search-with-lynx bind "
    alias "?d"="search-with-lynx duck "
    alias "?g"="search-with-lynx google "
fi

# editor
command -v vim &> /dev/null && alias vi="vim"
command -v nvim &> /dev/null && alias vim="nvim" vimdiff="nvim -d"

if command -v sudo &> /dev/null ; then
    alias sudo="sudo "

    wsudo () {
        if command -v $1 &> /dev/null ; then
            alias $1="sudo $1 "
        fi
    }

    # always execute commands with sudo
    for cmd in mount umount poweroff reboot shutdown showkey su ; do
        wsudo $cmd
    done; unset cmd

    #--- Gentoo
    if command -v emerge &> /dev/null ; then
        alias emerge="sudo emerge --ask "
    fi
    for cmd in emaint eselect ; do
        wsudo $cmd
    done; unset cmd
fi

# mess
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
if command -v symfony-cli &> /dev/null ; then
    alias symfony="symfony-cli"
fi
if command -v batcat &> /dev/null ; then
    alias bat="batcat"
fi
