#!/bin/zsh

export TERMINAL="st"
export EDITOR="vi"
export BROWSER="librewolf"

# Custom scripts
export PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/statusbar-blocks/bin"

# Home
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share

# X
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XRESOURCES="$XDG_CONFIG_HOME/x11/xresources"

# Shell
export ALIASRC="$XDG_CONFIG_HOME/shell/aliasrc"

# Zsh
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
export ZSHRC=${ZDOTDIR}/.zshrc
export HISTFILE=${XDG_DATA_HOME}/history

