#!/bin/zsh

export TERMINAL="st"
export EDITOR="vim"
export PAGER="less"
export BROWSER="librewolf"

# home
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

# x
export XINITRC=${XDG_CONFIG_HOME}/x11/xinitrc
export XRESOURCES=${XDG_CONFIG_HOME}/x11/xresources
export XAUTHORITY=${XDG_RUNTIME_DIR}/Xauthority
export ERRFILE=${XDG_CACHE_HOME}/X11/xsession-errors

# shell
export ALIASRC=${XDG_CONFIG_HOME}/shell/aliasrc
export STARSHIP_CONFIG=${XDG_CONFIG_HOME}/shell/starship/starship.toml

# zsh
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
export ZSHRC=${ZDOTDIR}/.zshrc
export HISTFILE=${XDG_DATA_HOME}/history

# docker
export DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker

# npm
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm

# gpg
export GNUPGHOME=${XDG_DATA_HOME}/gnupg

# other
export CARGO_HOME=${XDG_DATA_HOME}/cargo
export COMPOSER_PATH=${XDG_CONFIG_HOME}/composer
export GOMODCACHE=$XDG_CACHE_HOME/go/mod
export GOPATH=${XDG_DATA_HOME}/go
export RUSTUP_HOME=${XDG_DATA_HOME}/rustup
export WGETRC=${XDG_CONFIG_HOME}/wget/wgetrc
export MYSQL_HISTFILE=${XDG_CONFIG_HOME}/mysql_history
export PARALLEL_HOME=${XDG_CONFIG_HOME}/parallel
export SONARLINT_USER_HOME=${XDG_DATA_HOME}/sonarlint

# ruby bundler
export BUNDLE_USER_CONFIG=${XDG_CONFIG_HOME}/bundle
export BUNDLE_USER_CACHE=${XDG_CACHE_HOME}/bundle
export BUNDLE_USER_PLUGIN=${XDG_DATA_HOME}/bundle

# Runtime
export TMUX_TMPDIR=${XDG_RUNTIME_DIR}/tmux

# dwm fix
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java

# bun
export BUN_INSTALL=${XDG_STATE_HOME}/bun

# pnpm
export PNPM_HOME=${XDG_DATA_HOME}/pnpm
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# path
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.local/bin/local"
PATH="$PATH:$HOME/.local/bin/statusbar-blocks/bin"
PATH="$PATH:$CARGO_HOME/bin"
PATH="$PATH:$COMPOSER_PATH/vendor/bin"
PATH="$PATH:$GOPATH/bin"
PATH="$PATH:$BUN_INSTALL/bin"

export PATH
