#!/bin/zsh

export TERMINAL="st"
export EDITOR="vim"
export PAGER="less"
export BROWSER="librewolf"

# home
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

# x
export XINITRC=${XDG_CONFIG_HOME}/x11/xinitrc
export XRESOURCES=${XDG_CONFIG_HOME}/x11/xresources

# shell
export ALIASRC=${XDG_CONFIG_HOME}/shell/aliasrc
export STARSHIP_CONFIG=${XDG_CONFIG_HOME}/shell/starship/starship.toml

# zsh
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
export ZSHRC=${ZDOTDIR}/.zshrc
export HISTFILE=${XDG_DATA_HOME}/history

# npm
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm

# other
export CARGO_HOME=${XDG_DATA_HOME}/cargo
export GOMODCACHE=$XDG_CACHE_HOME/go/mod
export GOPATH=${XDG_DATA_HOME}/go
export WGETRC=${XDG_CONFIG_HOME}/wget/wgetrc

# Runtime
export TMUX_TMPDIR=${XDG_RUNTIME_DIR}/tmux

# dwm fix
export _JAVA_AWT_WM_NONREPARENTING=1

# path
PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/statusbar-blocks/bin"
PATH="$PATH:$CARGO_HOME/bin"
PATH="$PATH:$GOPATH/bin"

export PATH
