#!/bin/sh

runcmd () {
	cmd=$(echo $1 | awk '{print $1;}')
	if command -v ${cmd} &> /dev/null; then
		killall ${cmd} &> /dev/null
		eval "$1" &> /dev/null &
	fi
}

runcmds () {
	for cmd in $1; do
		runcmd ${cmd}
	done >/dev/null 2>&1
}


xrandr --dpi 96
xresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
[[ -f ${xresources} ]] && xrdb -merge ${xresources}

runcmds "setwallpaper dwmblocks dunst unclutter xcompmgr"
runcmd "pulseaudio -d"

pidof -sx dwm > /dev/null || dwm

