#!/bin/sh

runcmd () {
    cmd=$(echo $1 | awk '{print $1;}')
    if command -v $cmd &> /dev/null; then
        killall $cmd &> /dev/null
        eval "$1" &> /dev/null &
    fi
}

runcmds () {
    for cmd in $1; do
        runcmd $cmd
    done >/dev/null 2>&1
}

# Keyboard
setxkbmap -layout us,sk -option 'grp:win_space_toggle'
xbindkeys -f ${XDG_CONFIG_HOME:-$HOME/.config}/xbindkeys/xbindkeysrc

# Display
xrandr --dpi 96
xresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
[ -f $xresources ] && xrdb -merge "$xresources"

runcmd "pulseaudio --daemonize"
runcmds "dunst setwallpaper xcompmgr unclutter dwmblocks"

pidof -sx dwm > /dev/null || dwm
